// packages/ui/src/icons.ts
import {
  ArrowRight, Check, ChevronsUpDown, Circle, Copy, Edit, ExternalLink, File, HelpCircle, Home,
  Loader2, Mail, MessageSquare, Moon, Plus, PlusCircle, RefreshCw, Search, Server, Settings,
  Share2, Shield, Sun, Trash, User, Wand, Workflow, X, Tv, BookOpen as MangaIcon, SearchCode, Puzzle, MonitorPlay, Info, Star, List, AlertTriangle, LayoutGrid, CloudSun, Calendar as CalendarIcon, Package, MonitorSmartphone
} from 'lucide-react';

export const Icons = {
  arrowRight: ArrowRight,
  check: Check,
  chevronDown: ChevronsUpDown,
  chevronsUpDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  refreshCw: RefreshCw,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  user: User,
  wand: Wand,
  tv: Tv,
  manga: MangaIcon,
  ocr: SearchCode,
  puzzle: Puzzle,
  videoPlay: MonitorPlay,
  info: Info,
  star: Star,
  list: List,
  alertTriangle: AlertTriangle,
  layoutGrid: LayoutGrid,
  cloudSun: CloudSun,
  calendarIcon: CalendarIcon,
  packageIcon: Package,
  desktopIcon: MonitorSmartphone,
};